### ISSUE TITLE
small sugestion

### ISSUE THREAD

**Issue by Aokromes** [coddec/Classic-Shell#10]
Since idk how to reach you on a better way...
How about suggest Ivo Beltchev to buy http://www.classicshell.net/ and continue to maintain the domain there?

**Comment by coddec** [comment]
@Aokromes 
Ivo still owns http://www.classicshell.net/ see http://www.classicshell.net/forum/viewtopic.php?f=4&t=8147


> I will keep the MediaFire download mirror for another 6 months. The forum on http://www.classicshell.net/forum/ will stay open until the end of 2018, however I will not frequently participate in the discussions.

You can give it a try to send him a private message or reply to that thread I guess.

**Comment by Aokromes** [comment]
i mean, you must contact him :)

**Comment by coddec** [comment]
@Aokromes 

> i mean, you must contact him and sugest him to transfer the domain to you.

I won't have enough time and fund to manage and support the website though.

**Comment by Aokromes** [comment]
Ok :) a pity if someone gets the domain when it expires.
