### ISSUE TITLE
Classic Start Menu does not start autamatically in Windows 10 April Update

### ISSUE THREAD

**Issue by jedikalimero** [coddec/Classic-Shell#21]
Since my PC updated Windows 10 to the April 2018 Update, Classic Start Menu does not appear anymore when I click on the Start button. Instead, I get the regular Windows 10 Start menu.

If I start it manually, then I have the Classic Star Menu until I log out or turn off the computer.
I have tried in the settings to uncheck "Start automatically for this user" under "General Behavior", restart the computer, check it again and restart again (Sometimes this technique works in other programs) but no way.
The only way I have found to bypass this issue is to add a link to Classic Start Menu in the Startup folder, but the option in the settings doesn't seem to work anymore.

**Comment by coddec** [comment]
New issues should be opened at https://github.com/passionate-coder/Classic-Start/issues
No need to open duplicate issues.
And answer is here: https://github.com/passionate-coder/Classic-Start/issues/5
(For other's as reference in the future)
Thanks!
