### ISSUE TITLE
Updating Classic Start Menu to keep up with Windows 10

### ISSUE THREAD

**Issue by jedikalimero** [coddec/Classic-Shell#22]
When Classic Shell was released, its main intention was to bring back some of the useful things that Microsoft in their infinite stupidity had decided to remove or change into a less useful behaviour.
Classic Start Menu has three different styles: a Classic style, a classic with two columns and a Windows 7 style.
I use the Windows 7 style (in conjunction with cascading programs submenu) because this is the one that offers more useful options since it includes things that were introduced in Windows 7 and Vista but were not available in Windows XP (the classic Style).

It happens that Windows 10 has also introduced some useful things in its Start Menu (not much but a few)  but these things are not available in Classic Start Menu. One of them is an icon to access the Configuration window. We still have the Control Panel but many options have been moved to the Configuration window so nowadays you have to use it like it or not. I think a link to the Configuration in the right column would be great.

The other thing I miss is the mosaics panel introduced with Metro. I know many people hates this mosaic but it can be useful for many people too, so It wouldn't hurt anyone if Classic Start Menu had the option to include it as a third rightmost column that could be disabled in the settings for the people who prefer to not have it.

I know you can still access the regular Windows 10 start menu by shift-clicking Start, but it would be easier for the user experience to include this two things directly into Classic Start Menu.

Last but not least, we should also look into what Windows 8 and 10 have introduced to the File Explorer that we are missing by using Classic Explorer. (I don't want to get into details here but I think this could be a theme for another discussion).

**Comment by ge0rdi** [comment]
> I think a link to the Configuration in the right column would be great.

You can add `PC Settings` link in `Customize Start Menu` tab of Classic Shell's settings.

**Comment by jedikalimero** [comment]
Great! I didn't know it!

**Comment by coddec** [comment]
@jedikalimero 
As ge0rdi said, you can add link in Customize Start Menu tab of Classic Shell's settings.

If you your still not sure how to do it, here it is:
1. Open `Customize Start Menu` tab of Classic Shell's settings.
	- Right click on Start menu icon
	- Click on Settings
	- Click on `Customize Start Menu` tab
2. Right click on any of commands listed
3. Click on Insert new item, or press `Insert` key on you keyboard
4. Choose `Custom` option from the drop down list under `command column`.
5. Double click on the icon on the left
6. Put `ms-settings:` as `command`
7. Put `Windows 10 Settings` or whatever text you like to show up on the menu as `Label`
8. Put `shell32.dll, 16826` as icon
9. Save it by click on `OK`
10. Exit the settings by click on `OK`

The Settings menu entry you've created will show on the right hand side of the start menu.

**Comment by blackcrack** [comment]
http://lee-soft.com/windows-start-buttons/

have fun :) 

best regards
Blacky

**Comment by coddec** [comment]
@jedikalimero 
Actually, I just found that it's included within classicshell itself.
Under 'Customize Start Menu' Tab

![s](https://user-images.githubusercontent.com/12678338/40310769-3bf38cec-5d51-11e8-972f-d26f6020ac90.png)

**Comment by mailinglists35** [comment]
> You can add PC Settings link in Customize Start Menu tab of Classic Shell's settings.

I have v4.3.1 and pc settings was there by default, i didn't do anything to enable it!
