### ISSUE TITLE
Problem with Open Shell

### ISSUE THREAD

**Issue by johnOswestry** [coddec/Classic-Shell#41]
Hi I hope someone might be able to help. We have Open 4_4_142 on two laptops. There have been no problems over the years until my wife suddenly had things go wrong. The W10 start andW10 desktop with basic tiles appeared in place of the Open setup and desk top shortcuts she uses. The taskbar was the basic W10 one as well. I have uninstalled and after re downloading and reinstalled Open Shell, I used my setting but its now a mix of open shell start batten, click on it and the Open Shell W7 style start is there but with The W10 desktop and task bar. To confuse things as I have tried things the old desktop can be seen on occasion but it goes back to the W10 one. Sorry if this is a bit confusing, it in my younger years it would be an interesting challenge, but now its just a pain and my wife is finding it very difficult to cope with the screen as it is.

**Comment by ghost** [comment]
We can't help you here. Ask in open shell

**Comment by blackcrack** [comment]
Open-Shell is the successor Project of WinNT Custom Startmenu :

https://github.com/Open-Shell/Open-Shell-Menu/issues
https://github.com/Open-Shell/Open-Shell-Menu
Releases:
https://github.com/Open-Shell/Open-Shell-Menu/releases
Nightly's:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts

best

**Comment by blackcrack** [comment]
https://github.com/Open-Shell/Open-Shell-Menu
