### ISSUE TITLE
Wish to have the Windows 8.1 Theme

### ISSUE THREAD

**Issue by ghost** [coddec/Classic-Shell#46]
It would be wonderful if you can get me back the full screen start menu with charms bar, also the aero taskbar, also teh old system icons.

Thanks so much!

Shawn

**Comment by ghost** [comment]
Also I want the windows notifications to be able to on the top right please :) Thanks

**Comment by MartinX3** [comment]
Thank you, that you will do it for us @Shawnloveshorses161 because no one else can do it :)

**Comment by ghost** [comment]
HI Martin, sorry for teh confusion, I should have raised the other request to the dev of the Winareotweaker, well you could with Open Shell bring back a full screen startmeu option along with the already 7 options. are you able to do that?

**Comment by MartinX3** [comment]
@Shawnloveshorses161 how much would you like to pay for the ordered programming?

**Comment by ghost** [comment]
Well Martin, this isn't a necessity for me to have a windows 8 theme but it would be nice, though do consider this feature request. Anyways thanks for a amazing program!

have a wonderful day!

Shawn
