### ISSUE TITLE
What license did the original Classic shell use?

### ISSUE THREAD

**Issue by IkeKap** [coddec/Classic-Shell#5]
Was the MIT license the license the original program used or is this a diff license? 
Btw, Thanks for taking the time to rehost the code

**Comment by crr0004** [comment]
It's been re-released under MIT. See sourceforge.

**Comment by coddec** [comment]
The source code and license are all uploaded here as it is, exactly same as original ones.

The MIT license was included from Ivo Beltchev's original source code (Under ClassicShellSrc Folder): https://github.com/coddec/Classic-Shell/blob/master/ClassicShellSrc/LICENSE.txt

The sourceforge managed by him also indicates it is under MIT license: https://sourceforge.net/projects/classicshell/?source=directory

;)

Here is the screenshot of the sourceforge:
![screen_mit](https://user-images.githubusercontent.com/12678338/33603597-2542c9d6-da07-11e7-8543-8328f1691fc5.png)

**Comment by mailinglists35** [comment]
thank you for uploading/updating source to github. this way others can pick up and easily fork!

**Comment by coddec** [comment]
@mailinglists35 
> thank you for uploading/updating source to github. this way others can pick up and easily fork!

Exactly what I was thinking ;)

Cheers!
