### ISSUE TITLE
Remove binaries from source tree

### ISSUE THREAD

**Issue by ge0rdi** [coddec/Classic-Shell#8]
I'd like to propose removal of these folders from source tree:
`Binary,Executable`
`ClassicShellPDB`

They are part of release, so they should be attached on _Releases_ page.

Moreover they bloat repo history and every contributor has to unnecessarily download them during clone/fetch.

In fact there is no way to get rid of them from history (since they were pushed already), but at least there shouldn't be new binaries pushed to the repo in the future.

**Comment by ge0rdi** [comment]
Thank you.

**Comment by jimbo1qaz** [comment]
should you squash everything and force-push to clean up the repo? Or is it bad practice to force-push common repos?

**Comment by ge0rdi** [comment]
@jimbo1qaz 
While I agree that it should've been single commit, changing a history of publicly available repo is definitely not a good idea.
It will cause troubles to those who already cloned (and did some work on the repo).
